controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
        publish_rate: 50.0

    scara_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
scara_trajectory_controller:
  ros__parameters:
    command_interfaces: 
      - position
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
    command_joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
    state_interfaces: 
      - position
      - velocity
    state_publish_rate: 25.0
